export const FETCHING_FLIGHTS_DATA = 'FETCHING_FLIGHTS_DATA';
export const FETCHING_FLIGHTS_DATA_SUCCESS = 'FETCHING_FLIGHTS_DATA_SUCCESS';
export const FETCHING_FLIGHTS_DATA_FAIL = 'FETCHING_FLIGHTS_DATA_FAIL';